### ISSUE TITLE
System and GPU requirements

### ISSUE THREAD

**Issue by YantianZha** [AdaCompNUS/DaXBench#3]
Hello, thanks for the great work. Could you let me know what is the requirements of operating system and GPU? Do you need Ubuntu and what version? Is an NVIDIA gpu necessary?

**Comment by siwei0729** [comment]
Hello,

Thanks for your question on the requirements of the operating system and GPU. For the best performance and efficiency, we highly recommend using Ubuntu 20 and 22 as your operating system. 

In terms of hardware, while an Nvidia GPU isn't absolutely necessary, it is strongly preferred. This is due to its ability to greatly speed up processes. However, the system can still run on CPU only, albeit at a slow speed.
